/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framesCruds;

import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class frameUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frameUsuario
     */
    public frameUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Formulario Usuario");
        setIconImage(new ImageIcon(getClass().getResource("/hotelIcono.png")).getImage());
        this.labelOculto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelNombreU = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNombreU = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        labelImageRegresar = new javax.swing.JLabel();
        labelVer = new javax.swing.JLabel();
        labelOculto = new javax.swing.JLabel();
        labelGuardar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(50, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 36)); // NOI18N
        labelTitulo.setText("Formulario Usuario");
        jPanel1.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        labelNombre.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        labelNombre.setText("Ingrese el nombre de usuario:");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        labelContraseña.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        labelContraseña.setText("Ingrese la contraseña para usuario:");
        jPanel1.add(labelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        labelCorreo.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        labelCorreo.setText("Ingrese el correo electrónico del usuario:");
        jPanel1.add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        labelNombreU.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        labelNombreU.setText("Nombre completo del usuario:");
        jPanel1.add(labelNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        labelTelefono.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        labelTelefono.setText("Número de telefóno del usuario:");
        jPanel1.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 350, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 290, -1));
        jPanel1.add(txtNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 350, -1));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 280, -1));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 320, -1));

        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 870, 160));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 870, 20));

        labelImageRegresar.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        labelImageRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha-izquierda.png"))); // NOI18N
        labelImageRegresar.setText("Regresar");
        labelImageRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelImageRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImageRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(labelImageRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        labelVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verl.png"))); // NOI18N
        labelVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVerMouseClicked(evt);
            }
        });
        jPanel1.add(labelVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, 30));

        labelOculto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oculto.png"))); // NOI18N
        labelOculto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelOcultoMouseClicked(evt);
            }
        });
        jPanel1.add(labelOculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        labelGuardar.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        labelGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-solid-60.png"))); // NOI18N
        labelGuardar.setText("Guardar");
        labelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(labelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        jLabel1.setText("Editar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borrar.png"))); // NOI18N
        jLabel2.setText("Eliminar");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void labelVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVerMouseClicked
        labelVer.setVisible(false);
        labelOculto.setVisible(true);
        txtContraseña.setEchoChar((char)0);
    }//GEN-LAST:event_labelVerMouseClicked

    private void labelOcultoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOcultoMouseClicked
        labelVer.setVisible(true);
        labelOculto.setVisible(false);
        txtContraseña.setEchoChar('*');
    }//GEN-LAST:event_labelOcultoMouseClicked

    private void labelImageRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImageRegresarMouseClicked
        menu abrir = new menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelImageRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelGuardar;
    private javax.swing.JLabel labelImageRegresar;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreU;
    private javax.swing.JLabel labelOculto;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVer;
    private javax.swing.JTable tablaUsuario;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreU;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
