/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framesCruds;

import com.formdev.flatlaf.intellijthemes.FlatXcodeDarkIJTheme;

/**
 *
 * @author PC
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Login");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelHotel = new javax.swing.JLabel();
        labelImagehotel = new javax.swing.JLabel();
        labelImage = new javax.swing.JLabel();
        labelImageUser = new javax.swing.JLabel();
        labelImageKey = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        labelMensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(50, 51, 51));
        jPanel1.setLayout(null);

        labelHotel.setBackground(new java.awt.Color(0, 0, 0));
        labelHotel.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        labelHotel.setForeground(new java.awt.Color(51, 51, 51));
        labelHotel.setText("Hotel Dulce Sueño");
        jPanel1.add(labelHotel);
        labelHotel.setBounds(100, 60, 120, 20);

        labelImagehotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotel-regular-96 (1).png"))); // NOI18N
        jPanel1.add(labelImagehotel);
        labelImagehotel.setBounds(110, 10, 100, 50);

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Captura (2).png"))); // NOI18N
        jPanel1.add(labelImage);
        labelImage.setBounds(0, 0, 320, 500);

        labelImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-circle-solid-96.png"))); // NOI18N
        jPanel1.add(labelImageUser);
        labelImageUser.setBounds(340, 110, 96, 100);

        labelImageKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key-solid-96.png"))); // NOI18N
        jPanel1.add(labelImageKey);
        labelImageKey.setBounds(340, 270, 110, 100);

        txtUser.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        txtUser.setText("Ingrese su nombre de usuario");
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        jPanel1.add(txtUser);
        txtUser.setBounds(450, 160, 210, 30);

        labelMensaje.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelMensaje.setText("Inicio de sesion");
        jPanel1.add(labelMensaje);
        labelMensaje.setBounds(390, 20, 270, 50);

        jButton1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jButton1.setText("Iniciar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 410, 130, 30);

        txtPassword.setText("jPasswordField1");
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(txtPassword);
        txtPassword.setBounds(460, 310, 200, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        txtUser.setText("");
    }//GEN-LAST:event_txtUserMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu abrir = new menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            UIManager.setLookAndFeel( new FlatLightLaf() );
            FlatXcodeDarkIJTheme.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHotel;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelImageKey;
    private javax.swing.JLabel labelImageUser;
    private javax.swing.JLabel labelImagehotel;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
